# -*- coding: utf-8 -*-
"""project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JqLV6GRTS1vTbxa7b1EoJxdTUraatiDU
"""

# =========================================
# 1. IMPORT LIBRARIES
# =========================================
import pandas as pd
import numpy as np
from google.colab import files # Added for file upload

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR

from sklearn.metrics import mean_squared_error, r2_score


from google.colab import files
uploaded = files.upload()

import pandas as pd
df=pd.read_csv('ai_impact_student_performance_dataset.csv')
df.head()

# =========================================
# 3. ANALYSE DATA
# =========================================
print("First 5 rows:\n", df.head())
print("\nInfo:\n")
print(df.info())
print("\nMissing Values:\n", df.isnull().sum())

# =========================================
# 4. HANDLE NULL VALUES (REPLACE WITH MEAN)
import pandas as pd
import numpy as np

# Load dataset (if not already loaded)
df = pd.read_csv("ai_impact_student_performance_dataset.csv")

# Check missing values before
print("Missing values BEFORE:\n", df.isnull().sum())

# Fill numeric columns with mean
for col in df.select_dtypes(include=np.number):
    mean_value = df[col].mean()
    df[col].fillna(mean_value, inplace=True)

# Fill categorical columns with mode (recommended)
for col in df.select_dtypes(include='object'):
    mode_value = df[col].mode()[0]
    df[col].fillna(mode_value, inplace=True)

# Check missing values after
print("\nMissing values AFTER:\n", df.isnull().sum())

# Preview dataset
print("\nFirst 5 rows:\n", df.head())

# =========================================
# DATASET CLEANING (COMPLETE PIPELINE)
# =========================================

import pandas as pd
import numpy as np

# =========================================
# 1. LOAD DATA
# =========================================
df = pd.read_csv("ai_impact_student_performance_dataset.csv")

print("Initial Shape:", df.shape)

# =========================================
# 2. BASIC INFO
# =========================================
print("\nColumns:\n", df.columns)
print("\nData Types:\n", df.dtypes)

# =========================================
# 3. REMOVE DUPLICATES
# =========================================
df.drop_duplicates(inplace=True)
print("\nAfter removing duplicates:", df.shape)

# =========================================
# 4. HANDLE MISSING VALUES
# =========================================

# Check missing values
print("\nMissing Values BEFORE:\n", df.isnull().sum())

# Fill numeric columns with mean
for col in df.select_dtypes(include=np.number):
    df[col].fillna(df[col].mean(), inplace=True)

# Fill categorical columns with mode
for col in df.select_dtypes(include='object'):
    df[col].fillna(df[col].mode()[0], inplace=True)

print("\nMissing Values AFTER:\n", df.isnull().sum())

# =========================================
# 5. CLEAN TEXT DATA (REMOVE EXTRA SPACES)
# =========================================
for col in df.select_dtypes(include='object'):
    df[col] = df[col].str.strip()

# =========================================
# 6. CONVERT DOLLAR ($) TO NUMERIC (OPTIONAL)
# =========================================
def clean_dollar(x):
    try:
        if isinstance(x, str):
            return float(x.replace('$', '').replace(',', ''))
        return x
    except:
        return np.nan

# Example column (change if needed)
if 'salary' in df.columns:
    df['salary'] = df['salary'].apply(clean_dollar)

# =========================================
# 7. DATA TYPE CONVERSION
# =========================================
# Convert numeric columns stored as object
for col in df.columns:
    try:
        df[col] = pd.to_numeric(df[col])
    except:
        pass

# =========================================
# 8. OUTLIER HANDLING (OPTIONAL)
# =========================================
# Remove extreme values using IQR method
for col in df.select_dtypes(include=np.number):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    df = df[(df[col] >= Q1 - 1.5 * IQR) & (df[col] <= Q3 + 1.5 * IQR)]

# =========================================
# 9. FINAL CHECK
# =========================================
print("\nFinal Shape:", df.shape)
print("\nFinal Missing Values:\n", df.isnull().sum())

# Preview cleaned dataset
print("\nCleaned Data:\n", df.head())

# =========================================
# SAVE CLEAN DATA (OPTIONAL)
# =========================================
df.to_csv("cleaned_dataset.csv", index=False)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
import numpy as np

# Load dataset
df = pd.read_csv("ai_impact_student_performance_dataset.csv")

# --- Preprocessing Steps to handle categorical data (added to address ValueError) ---
# Handle null values for both numeric and categorical columns
# Fill numeric columns with mean
for col in df.select_dtypes(include=np.number):
    df[col] = df[col].fillna(df[col].mean())

# Fill categorical columns with mode
for col in df.select_dtypes(include='object'):
    mode_value = df[col].mode()[0]
    df[col] = df[col].fillna(mode_value)

# Apply Label Encoding to categorical columns
le = LabelEncoder()
for col in df.select_dtypes(include='object'):
    # Convert to string first to handle potential mixed types or non-string objects gracefully
    df[col] = le.fit_transform(df[col].astype(str))
# --- End Preprocessing Steps ---

# -----------------------------
# Separate Features & Target
# -----------------------------
X = df.drop(['final_score'], axis=1)
y = df['final_score']

# -----------------------------
# Train-Test Split (BEST PRACTICE)
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# =========================================
# 1. STANDARD SCALER
# =========================================
sc = StandardScaler()

X_train_std = sc.fit_transform(X_train)   # fit only on training data
X_test_std = sc.transform(X_test)         # transform test data

print("Standard Scaled Data (first 5 rows):\n", X_train_std[:5])

# =========================================
# 2. MIN-MAX SCALER
# =========================================
mm = MinMaxScaler()

X_train_mm = mm.fit_transform(X_train)
X_test_mm = mm.transform(X_test)

print("\nMinMax Scaled Data (first 5 rows):\n", X_train_mm[:5])

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load dataset (if not already loaded)
df = pd.read_csv("ai_impact_student_performance_dataset.csv")

# Check categorical columns
cat_cols = df.select_dtypes(include='object').columns
print("Categorical Columns:\n", cat_cols)

# Apply Label Encoding
le_dict = {}  # to store encoders for each column

for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))  # ensure all values are string
    le_dict[col] = le  # store encoder (useful later)

# Show result
print("\nFirst 5 rows after label encoding:\n", df.head())

# Optional: Check transformed data types
print("\nUpdated Data Types:\n", df.dtypes)

# =========================================
# 7. FEATURE & TARGET
print("Columns in dataset:\n", df.columns)

# Ensure target column exists
if 'final_score' not in df.columns:
    raise ValueError("Column 'final_score' not found in dataset")

# Optional: drop unnecessary columns (like ID)
cols_to_drop = ['student_id'] if 'student_id' in df.columns else []

# Define features (X) and target (y)
X = df.drop(cols_to_drop + ['final_score'], axis=1)
y = df['final_score']

# Display shapes
print("\nShape of X (features):", X.shape)
print("Shape of y (target):", y.shape)

# Preview data
print("\nX sample:\n", X.head())
print("\ny sample:\n", y.head())

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_scaled = sc.fit_transform(X)

# =========================================
# 9. TRAIN TEST SPLIT
# =========================================
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

# Check shapes
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

# =========================================
# 11. SVR (SUPPORT VECTOR REGRESSION)
# =========================================
svr = SVR(kernel='rbf')   # try 'linear', 'poly'
svr.fit(X_train, y_train)

y_pred_svr = svr.predict(X_test)

# =========================================
# EVALUATION
# =========================================
print("----- Linear Regression -----")
print("MSE:", mean_squared_error(y_test, y_pred_lr))
print("R2 Score:", r2_score(y_test, y_pred_lr))

print("\n----- SVR -----")
print("MSE:", mean_squared_error(y_test, y_pred_svr))
print("R2 Score:", r2_score(y_test, y_pred_svr))

# =========================================
# EXPLORATORY DATA ANALYSIS (EDA)
# =========================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("ai_impact_student_performance_dataset.csv")

# =========================================
# 1. BASIC OVERVIEW
# =========================================
print("First 5 Rows:\n", df.head())

print("\nDataset Shape:", df.shape)

print("\nColumns:\n", df.columns)

# 2. DATA TYPES & INFO
# =========================================
print("\nDataset Info:\n")
print(df.info())

# 3. STATISTICAL SUMMARY
# =========================================
print("\nStatistical Summary:\n", df.describe())

# 4. MISSING VALUES
# =========================================
print("\nMissing Values:\n", df.isnull().sum())

# 5. VALUE COUNTS (Categorical)
# =========================================
for col in df.select_dtypes(include='object'):
    print(f"\nValue counts for {col}:\n", df[col].value_counts())

import pandas as pd
import numpy as np

# =========================================
# LOAD YOUR DATASET
# =========================================
df = pd.read_csv("ai_impact_student_performance_dataset.csv")

# Set seed for reproducibility
np.random.seed(42)

# =========================================
# SELECT TARGET COLUMN FOR MISSING VALUES
# =========================================
col_name = 'final_score'   # 🔁 change if needed

if col_name in df.columns:

    # Select 10 random indices
    missing_index = np.random.choice(df.index, size=10, replace=False)

    # Insert NaN values
    df.loc[missing_index, col_name] = np.nan

    # Output
    print("Missing indices:\n", missing_index)
    print("\nRows with missing values:\n")
    print(df.loc[missing_index])

else:
    print(f"Column '{col_name}' not found in dataset.")

print("Columns:\n", df.columns)

# =========================================
# EXAMPLE FILTER (ADJUST BASED ON YOUR DATA)
# =========================================

# Calculate average of a numeric column
avg_score = df['final_score'].mean()

# Apply filtering
filtered_df = df[
    (df['study_hours_per_day'] > 3) &                 # example condition
    (df['final_score'] > avg_score)           # above average score
]

print("\nFiltered Data:\n", filtered_df)

print("Columns:\n", df.columns)

# =========================================
# SELECT A CATEGORICAL COLUMN
# =========================================
col = 'gender'   # 🔁 change if needed

if col in df.columns:
    df[col].value_counts().plot(kind='bar')

    plt.title(f"Count of {col}")
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.show()

else:
    print(f"Column '{col}' not found. Please choose a valid column.")

print("Columns:\n", df.columns)

# =========================================
# SELECT FEATURE & TARGET
# =========================================
# Example: study_hours → final_score
X = df[['study_hours_per_day']]     # feature
y = df['final_score']       # target

# =========================================
# TRAIN TEST SPLIT
# =========================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# =========================================
# MODEL TRAINING
# =========================================
model = LinearRegression()
model.fit(X_train, y_train)

# =========================================
# PREDICTION
# =========================================
y_pred = model.predict(X_test)

# =========================================
# VISUALIZATION
# =========================================
plt.scatter(X_test, y_test, label='Actual')
plt.plot(X_test, y_pred, linewidth=2, label='Predicted')

plt.xlabel('Study Hours')
plt.ylabel('Final Score')
plt.title('Linear Regression Model')
plt.legend()
plt.show()

# 7. CORRELATION MATRIX
# =========================================
plt.figure(figsize=(10, 6))
sns.heatmap(df.select_dtypes(include=['number']).corr(), annot=False, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# 8. BOXPLOT (Outliers detection)
# =========================================
plt.figure(figsize=(12, 6))
sns.boxplot(data=df.select_dtypes(include='number'))
plt.xticks(rotation=90)
plt.title("Boxplot for Outliers")
plt.show()

from sklearn.linear_model import LogisticRegression
import numpy as np

print("Columns:\n", df.columns)

# =========================================
# CREATE CLASSIFICATION TARGET
# =========================================
# Convert final_score into binary (High / Low)
threshold = df['final_score'].mean()

df['High_Performance'] = np.where(df['final_score'] > threshold, 1, 0)

# =========================================
# FEATURES & TARGET
# =========================================
X = df[['study_hours_per_day']]   # you can add more features
y = df['High_Performance']

# =========================================
# TRAIN TEST SPLIT
# =========================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# =========================================
# MODEL TRAINING
# =========================================
model = LogisticRegression()
model.fit(X_train, y_train)

# =========================================
# PREDICTION
# =========================================
# Example: student with 5 study hours
prediction = model.predict([[5]])
probability = model.predict_proba([[5]])

print("Prediction (0 = Low, 1 = High):", prediction)
print("Probability:", probability)

X = df[['study_hours_per_day', 'attendance_percentage']]   # ❌ corrected

# Target (for coloring)
y = df['final_score']

# =========================================
# SCALING
# =========================================
sc = StandardScaler()
X_scaled = sc.fit_transform(X)

# =========================================
# SCATTER PLOT
# =========================================
plt.scatter(X_scaled[:, 0], X_scaled[:, 1], c=y)

plt.title("Scatter Plot (Study Hours vs Attendance)")
plt.xlabel("Study Hours (scaled)")
plt.ylabel("Attendance (scaled)")
plt.colorbar(label="Final Score")

plt.show()

X = df[['study_hours_per_day', 'final_score']].values

# =========================================
# SCATTER PLOT
# =========================================
plt.scatter(X[:, 0], X[:, 1])

plt.xlabel("Study Hours")
plt.ylabel("Final Score")
plt.title("Correlation Scatter Plot")

plt.show()

col = 'gender'   # 🔁 change if needed

if col in df.columns:

    counts = df[col].value_counts()

    # =========================================
    # PIE CHART
    # =========================================
    plt.figure(figsize=(6, 6))

    plt.pie(
        counts,
        labels=counts.index,
        autopct='%1.1f%%',
        startangle=90
    )

    plt.title(f"Distribution of {col}")
    plt.axis('equal')   # makes circle perfect

    plt.show()

else:
    print(f"Column '{col}' not found. Try another column.")

plt.hist(X_scaled[:, 0], bins=20, color='skyblue', edgecolor='black')
plt.title("Histogram of Feature 1")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()

# 9. RELATIONSHIP ANALYSIS
# =========================================
# Example: Study hours vs Final Score
if 'study_hours' in df.columns and 'final_score' in df.columns:
    sns.scatterplot(x=df['study_hours'], y=df['final_score'])
    plt.title("Study Hours vs Final Score")
    plt.show()
# 10. TARGET DISTRIBUTION
# =========================================
if 'final_score' in df.columns:
    sns.histplot(df['final_score'], kde=True)
    plt.title("Final Score Distribution")
    plt.show()

# =========================================
# CORRELATION ANALYSIS (COMPLETE)
# =========================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("ai_impact_student_performance_dataset.csv")

# =========================================
# 1. SELECT NUMERICAL COLUMNS
# =========================================
num_df = df.select_dtypes(include='number')

# =========================================
# 2. CORRELATION MATRIX
# =========================================
corr_matrix = num_df.corr()

print("Correlation Matrix:\n", corr_matrix)

# =========================================
# 3. HEATMAP VISUALIZATION
# =========================================
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=False, cmap='coolwarm')

plt.title("Correlation Heatmap")
plt.show()

# =========================================
# 4. HIGH CORRELATION PAIRS (IMPORTANT)
# =========================================
# Find features with high correlation (>0.7)
threshold = 0.7

high_corr = []

for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if abs(corr_matrix.iloc[i, j]) > threshold:
            col1 = corr_matrix.columns[i]
            col2 = corr_matrix.columns[j]
            value = corr_matrix.iloc[i, j]
            high_corr.append((col1, col2, value))

print("\nHighly Correlated Features (>|0.7|):")
for item in high_corr:
    print(item)

# =========================================
# 5. CORRELATION WITH TARGET
# =========================================
if 'final_score' in corr_matrix.columns:
    print("\nCorrelation with Final Score:\n")
    print(corr_matrix['final_score'].sort_values(ascending=False))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score
from sklearn.preprocessing import StandardScaler

# =========================================
# LOAD YOUR DATASET
# =========================================
df = pd.read_csv("ai_impact_student_performance_dataset.csv")

print("Columns:\n", df.columns)

# =========================================
# SELECT NUMERICAL FEATURES ONLY
# =========================================
num_cols = df.select_dtypes(include=np.number).columns

# Drop target column if present
if 'final_score' in num_cols:
    num_cols = num_cols.drop('final_score')

X = df[num_cols].values

# =========================================
# FEATURE SCALING
# =========================================
sc = StandardScaler()
X_scaled = sc.fit_transform(X)

# =========================================
# K-MEANS EVALUATION
# =========================================
inertias = []
sil_scores = []
db_scores = []
ch_scores = []

K_range = range(2, 11)

for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X_scaled)

    inertias.append(km.inertia_)
    sil_scores.append(silhouette_score(X_scaled, labels))
    db_scores.append(davies_bouldin_score(X_scaled, labels))
    ch_scores.append(calinski_harabasz_score(X_scaled, labels))

# =========================================
# PLOTTING
# =========================================
fig, axes = plt.subplots(2, 2, figsize=(13, 9))

# Elbow Method
axes[0,0].plot(K_range, inertias, 'o-')
axes[0,0].set_title('Inertia (Elbow Method)')
axes[0,0].set_xlabel('Number of Clusters (K)')
axes[0,0].set_ylabel('Inertia')

# Silhouette Score
axes[0,1].plot(K_range, sil_scores, 'o-')
axes[0,1].set_title('Silhouette Score')
axes[0,1].set_xlabel('Number of Clusters (K)')
axes[0,1].set_ylabel('Score')

# Davies-Bouldin
axes[1,0].plot(K_range, db_scores, 'o-')
axes[1,0].set_title('Davies-Bouldin Score')
axes[1,0].set_xlabel('K')
axes[1,0].set_ylabel('Score')

# Calinski-Harabasz
axes[1,1].plot(K_range, ch_scores, 'o-')
axes[1,1].set_title('Calinski-Harabasz Score')
axes[1,1].set_xlabel('K')
axes[1,1].set_ylabel('Score')

plt.suptitle('K-Means Clustering Evaluation (Your Dataset)', fontsize=16)
plt.tight_layout()
plt.show()

from scipy.cluster.hierarchy import linkage, dendrogram
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# =========================================
# LOAD YOUR DATASET
# =========================================
df = pd.read_csv("ai_impact_student_performance_dataset.csv")

# =========================================
# SELECT NUMERICAL FEATURES
# =========================================
num_cols = df.select_dtypes(include=np.number).columns

# Remove target column if present
if 'final_score' in num_cols:
    num_cols = num_cols.drop('final_score')

X = df[num_cols].values

# =========================================
# FEATURE SCALING
# =========================================
sc = StandardScaler()
X_scaled = sc.fit_transform(X)

# =========================================
# DENDROGRAM PLOTS
# =========================================
fig, axes = plt.subplots(2, 2, figsize=(15, 10))

methods = ['ward', 'average']
subplot_axes = [axes[0,0], axes[0,1]]

for i, method in enumerate(methods):
    Z = linkage(X_scaled, method=method)

    dendrogram(
        Z,
        ax=subplot_axes[i],
        p=10,
        truncate_mode='lastp',
        show_contracted=True,
        leaf_font_size=9,
        leaf_rotation=90,
        color_threshold=Z[-3, 2],
        above_threshold_color='gray'
    )

    subplot_axes[i].set_title(f'Dendrogram ({method} method)')

plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

# =========================================
# LOAD YOUR DATASET
# =========================================
df = pd.read_csv("ai_impact_student_performance_dataset.csv")

# =========================================
# SELECT NUMERICAL FEATURES
# =========================================
num_cols = df.select_dtypes(include=np.number).columns

# Remove target column if present
if 'final_score' in num_cols:
    num_cols = num_cols.drop('final_score')

X = df[num_cols].values

# =========================================
# FEATURE SCALING
# =========================================
sc = StandardScaler()
X_scaled = sc.fit_transform(X)

# =========================================
# DBSCAN PARAMETERS
# =========================================
eps = 0.5
min_samples = 5

dbscan = DBSCAN(eps=eps, min_samples=min_samples)
db_labels = dbscan.fit_predict(X_scaled)

# =========================================
# RESULTS
# =========================================
n_clusters_db = len(set(db_labels)) - (1 if -1 in db_labels else 0)
n_noise = (db_labels == -1).sum()

print("DBSCAN Results:")
print("Clusters found:", n_clusters_db)
print("Noise points:", n_noise, "(labelled -1)")
print("Cluster sizes:", dict(zip(*np.unique(db_labels, return_counts=True))))

# =========================================
# SILHOUETTE SCORE
# =========================================
if n_clusters_db > 1:
    non_noise = db_labels != -1
    print("Silhouette (excluding noise):",
          silhouette_score(X_scaled[non_noise], db_labels[non_noise]))

# =========================================
# VISUALIZATION (FIRST TWO FEATURES)
# =========================================
unique_labels = set(db_labels)

colors = {-1: '#999999', 0: '#4C72B0', 1: '#55A868', 2: '#C44E52', 3: '#8172B2'}

plt.figure(figsize=(8, 6))

for lbl in unique_labels:
    mask = db_labels == lbl
    color = colors.get(lbl, '#000000')

    plt.scatter(
        X_scaled[mask, 0],
        X_scaled[mask, 1],
        c=color,
        label=f'Cluster {lbl}',
        s=50,
        alpha=0.7
    )

plt.title("DBSCAN Clusters (First Two Features)")
plt.xlabel("Feature 1 (scaled)")
plt.ylabel("Feature 2 (scaled)")
plt.legend()
plt.show()

df = pd.read_csv('ai_impact_student_performance_dataset.csv')

# Assuming 'performance_category' is the target column for classification example
TARGET = 'performance_category'

# Features would be all columns except 'student_id' and the TARGET
ORIGINAL_FEATURES = [col for col in df.columns if col not in ['student_id', TARGET]]

# Label encode the target if it's categorical
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['label'] = le.fit_transform(df[TARGET])

print('Shape:', df.shape)
print('Class distribution:\n', df[TARGET].value_counts())
df.head(6)

df = df.drop(columns=['sum', 'id'], errors='ignore')

# =========================================
# ENCODE CATEGORICAL DATA
# =========================================
for col in df.select_dtypes(include=['object', 'category']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))

# =========================================
# CORRELATION MATRIX
# =========================================
corr = df.corr()

# Mask upper triangle
mask = np.triu(np.ones_like(corr, dtype=bool))

# =========================================
# HEATMAP
# =========================================
plt.figure(figsize=(10, 8))

sns.heatmap(
    corr,
    annot=True,
    cmap='coolwarm',
    mask=mask,
    fmt='.2f',
    linewidths=0.5
)

plt.title("Correlation Matrix")
plt.tight_layout()
plt.show()

# ── 2A: Domain-inspired feature creation ──────────────────────────────────────
df_feat = df.copy()

# --- Ratio features ---
df_feat['Study_AI_Ratio'] = df_feat['study_hours_per_day'] / (df_feat['ai_usage_time_minutes'] + 1e-6)
df_feat['AI_Per_Prompt']  = df_feat['ai_usage_time_minutes'] / (df_feat['ai_prompts_per_week'] + 1e-6)

# --- Combined Scores ---
df_feat['Overall_Academic_Score'] = df_feat['last_exam_score'] + df_feat['assignment_scores_avg'] + df_feat['concept_understanding_score']
df_feat['Total_Engagement']     = df_feat['study_hours_per_day'] + df_feat['ai_usage_time_minutes'] / 60 # Convert minutes to hours

# --- Difference features ---
df_feat['Exam_Assignment_Diff'] = df_feat['last_exam_score'] - df_feat['assignment_scores_avg']

# --- Log transforms (reduce skewness) ---
df_feat['Log_Study_Hours']  = np.log1p(df_feat['study_hours_per_day'])
df_feat['Log_AIAccess_Time'] = np.log1p(df_feat['ai_usage_time_minutes'])

# --- Interaction feature ---
df_feat['Study_Attendance_Interaction'] = df_feat['study_hours_per_day'] * df_feat['attendance_percentage']

NEW_FEATURES = [
    'Study_AI_Ratio',
    'AI_Per_Prompt',
    'Overall_Academic_Score',
    'Total_Engagement',
    'Exam_Assignment_Diff',
    'Log_Study_Hours',
    'Log_AIAccess_Time',
    'Study_Attendance_Interaction'
]

print(f'Original features : {len(ORIGINAL_FEATURES)}')
print(f'Engineered features: {len(NEW_FEATURES)}')
print(f'Total features     : {len(ORIGINAL_FEATURES) + len(NEW_FEATURES)}')
df_feat[ORIGINAL_FEATURES + NEW_FEATURES].head(5).round(3)

df['performance'] = pd.cut(
    df['final_score'],
    bins=3,
    labels=['Low', 'Medium', 'High']
)

TARGET = 'performance'

# =========================================
# SELECT FEATURES
# =========================================
# Use numeric features
FEATURES = df.select_dtypes(include='number').columns.tolist()

# Remove target if present
if 'final_score' in FEATURES:
    FEATURES.remove('final_score')

# =========================================
# PLOTTING
# =========================================
palette = sns.color_palette('viridis', n_colors=len(df[TARGET].unique()))

fig, axes = plt.subplots(3, 3, figsize=(15, 12))
axes = axes.flatten()

for ax, feat in zip(axes, FEATURES):
    for category, color in zip(df[TARGET].unique(), palette):
        subset = df[df[TARGET] == category][feat]

        ax.hist(subset, bins=15, alpha=0.5,
                color=color, label=category)

    ax.set_title(feat, fontsize=10, fontweight='bold')
    ax.set_xlabel('Value')
    ax.legend(fontsize=7)

plt.suptitle(
    'Feature Distributions by Performance Level\n'
    '(Well-separated = more important features)',
    fontsize=13, fontweight='bold'
)

plt.tight_layout()
plt.show()

print("Columns:\n", df.columns)

# =========================================
# SELECT FEATURES
# =========================================
# Select all features except target
TARGET = 'final_score'

features = df.drop(columns=[TARGET], errors='ignore')

# =========================================
# HANDLE CATEGORICAL DATA (Label Encoding)
# =========================================
le_dict = {}

# Include both 'object' and 'category' dtypes for label encoding
for col in features.select_dtypes(include=['object', 'category']).columns:
    le = LabelEncoder()
    features[col] = le.fit_transform(features[col].astype(str))
    le_dict[col] = le

# =========================================
# APPLY POLYNOMIAL FEATURES
# =========================================
poly = PolynomialFeatures(degree=2, include_bias=False)

X_poly = poly.fit_transform(features)

# Get feature names
poly_names = poly.get_feature_names_out(features.columns)

# =========================================
# OUTPUT
# =========================================
print(f"\nOriginal features  : {features.shape[1]}")
print(f"Polynomial features: {len(poly_names)}")

print("\nFirst 20 Polynomial Feature Names:")
for i, name in enumerate(poly_names[:20]):
    print(f"{i+1:2d}. {name}")

df['label'] = pd.cut(
    df['final_score'],
    bins=3,
    labels=[0, 1, 2]   # Low, Medium, High
)

# =========================================
# PREPARE FEATURES
# =========================================
X = df.drop(columns=['final_score', 'label'], errors='ignore').copy()
y = df['label']

# =========================================
# ENCODE CATEGORICAL DATA
# =========================================
for col in X.select_dtypes(include=['object', 'category']).columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col].astype(str))

# =========================================
# APPLY ANOVA F-TEST
# =========================================
f_scores, p_values = f_classif(X, y)

fi_df = pd.DataFrame({
    'Feature': X.columns,
    'F-Score': f_scores,
    'p-value': p_values
}).sort_values('F-Score', ascending=False)

# =========================================
# VISUALIZATION
# =========================================
fig, ax = plt.subplots(figsize=(10, 6))

colors = ['green' if p < 0.05 else 'red' for p in fi_df['p-value']]

bars = ax.barh(fi_df['Feature'][::-1],
               fi_df['F-Score'][::-1],
               color=colors[::-1])

ax.set_xlabel('ANOVA F-Score (higher = more important)')
ax.set_title('Feature Importance using ANOVA F-Test')

# Add values on bars
for bar, val in zip(bars, fi_df['F-Score'][::-1]):
    ax.text(bar.get_width(), bar.get_y() + bar.get_height()/2,
            f'{val:.1f}', va='center', fontsize=8)

plt.tight_layout()
plt.show()

# =========================================
# TOP FEATURES
# =========================================
print("\nTop 5 most important features:")
print(fi_df.head(5))

df_feat['FinalScore_Bin'] = pd.cut(
    df_feat['final_score'],
    bins=[0, 40, 70, 100], # Example bins for final scores
    labels=['Low (<40)', 'Medium (40-70)', 'High (>70)']
)

print('FinalScore binning distribution:')
print(pd.crosstab(df_feat['FinalScore_Bin'], df_feat['performance_category']))

TARGET = 'final_score'
df_scaled = df.drop(columns=[TARGET, 'performance', 'performance_category', 'label'], errors='ignore').copy()

# =========================================
# ENCODE CATEGORICAL FEATURES
# =========================================
for col in df_scaled.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df_scaled[col] = le.fit_transform(df_scaled[col].astype(str))

# =========================================
# NUMERICAL DATA FOR SCALING
# =========================================
X_raw = df_scaled.values
feature_names = df_scaled.columns

# =========================================
# APPLY SCALERS
# =========================================
scalers = {
    'Original': X_raw,
    'StandardScaler': StandardScaler().fit_transform(X_raw),
    'MinMaxScaler': MinMaxScaler().fit_transform(X_raw),
    'RobustScaler': RobustScaler().fit_transform(X_raw),
}

# =========================================
# VISUALIZATION (BOXPLOTS)
# =========================================
fig, axes = plt.subplots(1, 4, figsize=(18, 5))

colors = ['#999999', '#4C72B0', '#55A868', '#C44E52']

for ax, (name, Xs), color in zip(axes, scalers.items(), colors):
    ax.boxplot(
        Xs,
        patch_artist=True,
        boxprops=dict(facecolor=color, alpha=0.6),
        medianprops=dict(color='black')
    )

    ax.set_xticklabels(feature_names, rotation=35, ha='right', fontsize=8)
    ax.set_title(name, fontweight='bold', fontsize=10)
    ax.set_ylabel('Value Range')

plt.suptitle(
    'Scaling Method Comparison — Same Data, Different Scale',
    fontsize=12, fontweight='bold'
)

plt.tight_layout()
plt.show()

SEED = 42

# =========================================
# CREATE TARGET (CLASSIFICATION)
# =========================================
# Convert final_score → classes
df['label'] = pd.cut(
    df['final_score'],
    bins=3,
    labels=[0, 1, 2]   # Low, Medium, High
)

# =========================================
# SELECT FEATURES
# =========================================
X = df.drop(columns=['final_score', 'label', 'performance_category', 'performance'], errors='ignore').copy()
y = df['label']

# =========================================
# ENCODE CATEGORICAL DATA
# =========================================
for col in X.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col].astype(str))

# =========================================
# TRAIN TEST SPLIT
# =========================================
X_tr, X_te, y_tr, y_te = train_test_split(
    X, y, test_size=0.25, stratify=y, random_state=SEED
)

# =========================================
# SCALING + SVM COMPARISON
# =========================================
scale_results = {}

for name, scaler in [
    ('No Scaling', None),
    ('StandardScaler', StandardScaler()),
    ('MinMaxScaler', MinMaxScaler()),
    ('RobustScaler', RobustScaler())
]:

    if scaler:
        Xtr_s = scaler.fit_transform(X_tr)
        Xte_s = scaler.transform(X_te)
    else:
        Xtr_s, Xte_s = X_tr.values, X_te.values

    svm = SVC(kernel='rbf', random_state=SEED)
    svm.fit(Xtr_s, y_tr)

    acc = accuracy_score(y_te, svm.predict(Xte_s))
    scale_results[name] = acc

# =========================================
# RESULTS
# =========================================
print("SVM Accuracy by Scaling Method:\n")

for name, acc in scale_results.items():
    bar = '█' * int(acc * 40)
    print(f"{name:18s}: {acc:.4f}  {bar}")

SEED = 42

# =========================================
# SELECT NUMERIC COLUMN
# =========================================
col = 'final_score'   # 🔁 change if needed

df_outlier = df[[col]].copy()

# =========================================
# (OPTIONAL) INJECT OUTLIERS FOR DEMO
# =========================================
np.random.seed(7)
out_idx = np.random.choice(df_outlier.index, size=5, replace=False)
df_outlier.loc[out_idx, col] = df_outlier[col].max() * 1.5

# =========================================
# IQR METHOD
# =========================================
Q1 = df_outlier[col].quantile(0.25)
Q3 = df_outlier[col].quantile(0.75)
IQR = Q3 - Q1

lo = Q1 - 1.5 * IQR
hi = Q3 + 1.5 * IQR

iqr_mask = (df_outlier[col] < lo) | (df_outlier[col] > hi)

# =========================================
# Z-SCORE METHOD
# =========================================
z = np.abs(stats.zscore(df_outlier[col]))
z_mask = z > 3

# =========================================
# ISOLATION FOREST
# =========================================
iso = IsolationForest(contamination=0.05, random_state=SEED)
iso_pred = iso.fit_predict(df_outlier[[col]])
iso_mask = iso_pred == -1

# =========================================
# RESULTS
# =========================================
print(f"IQR bounds: [{lo:.2f}, {hi:.2f}]")
print(f"Outliers — IQR: {iqr_mask.sum()} | Z-score: {z_mask.sum()} | IsoForest: {iso_mask.sum()}")

# =========================================
# VISUALIZATION
# =========================================
fig, axes = plt.subplots(1, 3, figsize=(14, 4))

methods = [
    ('IQR', iqr_mask),
    ('Z-Score (|z|>3)', z_mask),
    ('Isolation Forest', iso_mask)
]

for ax, (title, mask) in zip(axes, methods):
    ax.scatter(
        range(len(df_outlier)),
        df_outlier[col],
        c=['red' if m else 'blue' for m in mask],
        s=30,
        alpha=0.8
    )

    ax.set_title(f"{title}\nOutliers = Red", fontweight='bold')
    ax.set_xlabel("Index")
    ax.set_ylabel(col)

plt.suptitle("Outlier Detection Methods Comparison", fontweight='bold')
plt.tight_layout()
plt.show()

from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler # Import StandardScaler
from sklearn.metrics import f1_score
from sklearn.utils import resample # Import resample

df['label'] = pd.cut(df['final_score'], bins=3, labels=[0, 1, 2])

# =========================================
# PREPARE FEATURES
# =========================================
X = df.drop(columns=['final_score', 'label', 'performance', 'performance_category'], errors='ignore').copy()
y = df['label']

# Encode categorical features
for col in X.select_dtypes(include='object').columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col].astype(str))

# =========================================
# TRAIN TEST SPLIT
# =========================================
X_tr, X_te, y_tr, y_te = train_test_split(
    X, y, test_size=0.25, stratify=y, random_state=42
)

# =========================================
# FEATURE SCALING
# =========================================
scaler = StandardScaler()
X_tr_scaled = scaler.fit_transform(X_tr)
X_te_scaled = scaler.transform(X_te)

# =========================================
# STRATEGIES
# =========================================

# 1. No balancing
# Note: While 'no balancing', scaling is applied to all models for convergence
model1 = LogisticRegression(max_iter=2000) # Increased max_iter
model1.fit(X_tr_scaled, y_tr) # Use scaled data
pred1 = model1.predict(X_te_scaled) # Use scaled data

# 2. Class weight
model2 = LogisticRegression(class_weight='balanced', max_iter=2000) # Increased max_iter
model2.fit(X_tr_scaled, y_tr) # Use scaled data
pred2 = model2.predict(X_te_scaled) # Use scaled data

# 3. Oversampling (simple)
df_train = pd.concat([pd.DataFrame(X_tr_scaled, columns=X_tr.columns), y_tr.reset_index(drop=True)], axis=1)
max_class = df_train['label'].value_counts().max()

# Collect resampled groups
resampled_groups = []
for name, group in df_train.groupby('label', observed=False):
    resampled_group = resample(
        group,
        replace=True,
        n_samples=max_class,
        random_state=42
    )
    resampled_groups.append(resampled_group)

df_balanced = pd.concat(resampled_groups).reset_index(drop=True)

X_os = df_balanced.drop(columns='label')
y_os = df_balanced['label']

model3 = LogisticRegression(max_iter=2000) # Increased max_iter
model3.fit(X_os, y_os)
pred3 = model3.predict(X_te_scaled) # Use scaled test data

# Store predictions
strategies = {
    'No Balancing': pred1,
    'Class Weight': pred2,
    'Oversampling': pred3
}

# =========================================
# F1 SCORE CALCULATION
# =========================================
strategy_names = list(strategies.keys())
f1_scores = [f1_score(y_te, preds, average='macro')
             for preds in strategies.values()]

# =========================================
# VISUALIZATION
# =========================================
fig, ax = plt.subplots(figsize=(9, 5))

bars = ax.bar(strategy_names, f1_scores)

ax.set_ylim(0, 1)
ax.set_ylabel('Macro F1 Score')
ax.set_title('Imbalance Strategy Comparison')

# Show values
for bar, v in zip(bars, f1_scores):
    ax.text(bar.get_x() + bar.get_width()/2,
            bar.get_height() + 0.01,
            f'{v:.4f}', ha='center')

plt.tight_layout()
plt.show()

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df['label'] = pd.cut(
    df['final_score'],
    bins=3,
    labels=[0, 1, 2]   # Low, Medium, High
)

# =========================================
# FEATURES & TARGET
# =========================================
X = df.drop(columns=['final_score', 'label'], errors='ignore').copy()
y = df['label']

# =========================================
# ENCODE CATEGORICAL DATA
# =========================================
for col in X.select_dtypes(include=['object', 'category']).columns:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col].astype(str))

# =========================================
# TRAIN TEST SPLIT
# =========================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# =========================================
# DECISION TREE MODEL
# =========================================
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# =========================================
# PREDICTION
# =========================================
y_pred = model.predict(X_test)

# =========================================
# ACCURACY
# =========================================
acc = accuracy_score(y_test, y_pred)

print("Decision Tree Accuracy:", acc)

# =========================================
# EXTRA (OPTIONAL BUT IMPORTANT)
# =========================================
print("\nClassification Report:\n", classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

import matplotlib.pyplot as plt
import numpy as np

# Create subplots
fig, axes = plt.subplots(1, 2, figsize=(15, 8))

# =========================================
# 1. ARTIFICIAL NEURON DIAGRAM
# =========================================
ax = axes[0]
ax.set_xlim(0, 10)
ax.set_ylim(0, 10)
ax.axis('off')

# Neuron (circle)
circle = plt.Circle((5, 5), 1.2, color='red', alpha=0.85)
ax.add_patch(circle)

# Inputs
inputs = [('x1', 2.0, 7.5, 'w1'),
          ('x2', 2.0, 5.0, 'w2'),
          ('x3', 2.0, 2.5, 'w3')]

for name, x, y, w in inputs:
    ax.annotate('', xy=(3.8, 5), xytext=(x + 0.4, y),
                arrowprops=dict(arrowstyle='->', color='blue', lw=2))

    ax.text(x, y, name, ha='center', fontsize=13,
            bbox=dict(boxstyle='round', facecolor='#AEC6E8'))

    ax.text((x + 3.8) / 2, (y + 5) / 2, w,
            fontsize=10, color='blue')

# Bias
ax.text(4.2, 3.4, '+b', fontsize=12, fontweight='bold')

# Output arrow
ax.annotate('', xy=(8.5, 5), xytext=(6.2, 5),
            arrowprops=dict(arrowstyle='->', lw=4))

ax.text(9, 5, 'y', fontsize=14,
        bbox=dict(boxstyle='round', facecolor='#A3D5B5'))

# Title + formula
ax.text(5, 9.2, 'Artificial Neuron', ha='center',
        fontsize=14, fontweight='bold')

ax.text(5, 8.5, 'z = w1x1 + w2x2 + w3x3 + b\ny = σ(z)',
        ha='center', fontsize=10)

# =========================================
# 2. ACTIVATION FUNCTIONS
# =========================================
ax2 = axes[1]

z = np.linspace(-5, 5, 300)

# Plot functions
ax2.plot(z, 1/(1+np.exp(-z)), label='Sigmoid', lw=2)
ax2.plot(z, np.tanh(z), label='Tanh', lw=2)
ax2.plot(z, np.maximum(0, z), label='ReLU', lw=2)
ax2.plot(z, np.where(z > 0, z, 0.1*z), label='Leaky ReLU', lw=2)

# Axis lines
ax2.axhline(0)
ax2.axvline(0)

ax2.set_title("Activation Functions")
ax2.set_xlabel("z (input)")
ax2.set_ylabel("output")

ax2.legend()

# Annotation
ax2.annotate('ReLU is most used',
             xy=(2, 2), xytext=(1, -1),
             arrowprops=dict(arrowstyle='->'))

# =========================================
# FINAL DISPLAY
# =========================================
plt.suptitle("Deep Learning Fundamentals - Artificial Neuron", fontsize=14)
plt.tight_layout()
plt.show()